### ISSUE TITLE
运行有误

### ISSUE THREAD

**Issue by binibaichi** [SLY1311220942/demo-seata-springcloud#3]
楼主好，运行你的代码，在feign拦截器RequestInterceptor里面，String xid = RootContext.getXID();为null，得不到seata的xid，这是怎么回事？

**Comment by SLY1311220942** [comment]
你需要修改一下seata的源码修改方法在readme里有

**Comment by binibaichi** [comment]
按照楼主说的，修改了seata的源码v0.6.1（ThreadLocalContextCore），然后把编译过得两个.class文件，打到seata-server-0.6.1\distribution\lib\seata-core-0.6.1.jar，对应的目录下，运行seata，运行楼主程序，是无法获得xid的。。。。。。

**Comment by SLY1311220942** [comment]
不是打到seata-server-0.6.1里,是这个地方,seata-server不需要去动他
![image](https://user-images.githubusercontent.com/24586775/61275476-a25c9480-a7e0-11e9-8c28-4966b09a53c4.png)

**Comment by binibaichi** [comment]
了解，晕了。。。是打到依赖里是吧，谢谢，楼主，我再试试去

**Comment by binibaichi** [comment]
楼主，好了，谢谢！
